version: '3.1'
services:

  app:
    container_name: ${PROJECT_NAME}-app
    platform: ${PLATFORM}
    extends:
      file: ./shared/dockerfiles/templates/service.yml
      service: apache
    depends_on:
      - mysql
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    build:
      args:
        service: frontend
        PROJECT_NAME: ${PROJECT_NAME}
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        PHP_VERSION: ${PHP_VERSION}
        PATH_SERVICES: ${PATH_SERVICES}
        PATH_WORKDIR: ${PATH_WORKDIR}
        PATH_SERVER_ROOT: ${PATH_SERVER_ROOT}
    volumes:
      - "${PATH_SERVICES}/frontend:/var/www/frontend:rw"
      - "../${PROJECT_NAME}-app:${PATH_WORKDIR}:rw"
    working_dir: ${PATH_WORKDIR}
    command: >
      bash -c "./script/build-project.sh && /usr/sbin/apache2ctl -D FOREGROUND"

  mysql:
    image: mysql:5.7
    platform: ${PLATFORM}
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}-de
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: ${PLATFORM}
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - ${PHPMA_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

volumes:
  mysql_data:
  mongo_data:
  rabbit:
    driver: local
  apache-logs:
    driver_opts:
      type: none
      device: ./apache-logs/
      o: bind
  esdata01:
    driver: local


